name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    name: Terraform Format, Init, Plan and Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_aws_region: us-east-1
      TF_VAR_azure_location: East US
      TF_VAR_azure_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_azure_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_azure_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_azure_tenant_id: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Write tfvars from secret
        run: echo "${{ secrets.MULTICLOUD }}" > terraform.tfvars

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -var-file="terraform.tfvars"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false -var-file="terraform.tfvars"

